logic-screen
Pixolo-Team/RN-Expo-POC pull request #25
Opened 2024-01-19 16:27 UTC by Pratham3006

PR for login-screen

2024-02-06 16:55 UTC, anchanadarsh requested changes

2024-02-06 16:55 UTC, anchanadarsh commented on App.tsx
>  // PROVIDERS //
remove this

2024-02-06 16:55 UTC, anchanadarsh commented on src/contexts/authentication.context.tsx
> +		const userId = (await getDataFromLocalStorage(LocalStorageKeys.USER))._id;
Add comment 
// Get the userId from Local storage

2024-02-06 16:55 UTC, anchanadarsh commented on src/contexts/authentication.context.tsx
> +	/** Login the Usr Locally (within the App) */
Usr -> User

2024-02-06 16:55 UTC, anchanadarsh commented on src/contexts/authentication.context.tsx
> +		setUser(user);
Add comments
// Save user data in the user context

2024-02-06 16:55 UTC, anchanadarsh commented on src/contexts/authentication.context.tsx
> +			const userObject = await getDataFromLocalStorage(LocalStorageKeys.USER);
Add comments
// Get user and token from Local storage

2024-02-06 16:55 UTC, anchanadarsh commented on src/infrastructure/navigation/AppNavigation.tsx
> +import HomeScreen from "../../features/home/screens/Home.screen";
segregate imports

2024-02-06 16:55 UTC, anchanadarsh commented on src/infrastructure/navigation/AppNavigation.tsx
> +			{!isAuthenticated ? (
Add comments
If user is authenticated then show AuthStack else show HomeScreen

2024-02-19 16:50 UTC, aminabhay requested changes

2024-02-19 16:50 UTC, pixolopr commented on src/contexts/authentication.context.tsx
> +// OTHERS //
CONTEXTS

2024-02-19 16:50 UTC, aminabhay commented on src/contexts/authentication.context.tsx
> +		// Save user data in the user context
Capital U

2024-02-19 16:50 UTC, pixolopr commented on src/contexts/authentication.context.tsx
> +			// Get user and token from Local storage
capital U

2024-02-19 16:50 UTC, pixolopr commented on src/enums/analytics.ts
> +export enum FirebaseAnalyticsEvents {
just call it AnalyticsEvents

2024-02-19 16:50 UTC, pixolopr commented on src/features/account/screens/Login.screen.tsx
> +		// Log Event in firebase analytics when Login Screen is opened
Analytics
Don't use the word Firebase, keep it platform agnostic

2024-02-19 16:50 UTC, pixolopr commented on src/infrastructure/constants.ts
> +	MESSAGES_LIMIT: 50,
Remove unwanted.

2024-02-19 16:50 UTC, pixolopr commented on src/infrastructure/navigation/AppNavigation.tsx
> +			{/* If user is authenticated then show AuthStack else show HomeScreen */}
capital U, A

In comments do not use camelCase, PascalCase words. Use normal english like Home Screen

show the Home Screen

2024-02-19 16:50 UTC, pixolopr commented on src/services/api/users.api-service.ts
> +	userId: string | null
userId null kaise ho sakta hai

2024-02-19 16:50 UTC, pixolopr commented on src/types/account.d.ts
> +type LoginFormErrors = {
end with Data

2024-02-19 16:50 UTC, pixolopr commented on src/types/users.d.ts
> +interface Device {
type

2024-02-19 16:50 UTC, pixolopr commented on src/types/users.d.ts
> +interface Device {
DeviceData

2024-02-19 16:50 UTC, pixolopr commented on src/types/users.d.ts
> +interface UserCoreData {
type

2024-02-19 16:50 UTC, pixolopr commented on src/utils/validation.util.ts
> +};
Phone Number ka bhi validation Function bana do

2024-02-24 15:18 UTC, pixolopr requested changes

2024-02-24 15:18 UTC, pixolopr commented on src/contexts/authentication.context.tsx
> +		// Get the userId from Local storage
User ID

2024-02-24 15:18 UTC, pixolopr commented on src/enums/analytics.ts
> +	USER_SIGN_UP = "user_sign_up",
Add to this

USER_LOGIN
USER_LOGOUT

2024-02-24 15:18 UTC, pixolopr commented on src/features/account/screens/Login.screen.tsx
> +		logPageViewEvent("Login");
Make a new enum in analytics.enum.ts

PageNames
LOGIN = "Login"

And use it from here

2024-02-24 15:18 UTC, pixolopr commented on src/infrastructure/constants.ts
> +// Project ID
write in bracket (Expo Project ID)

2024-02-24 15:18 UTC, pixolopr commented on src/services/analytics.service.ts
> +/**  Will log the analytics events */
capital A

2024-02-24 15:18 UTC, pixolopr commented on src/services/analytics.service.ts
> +	// Get the userId from Local storage
User ID

2024-02-24 15:18 UTC, pixolopr commented on src/services/analytics.service.ts
> +/** Will log the analytics screen view event */
Capital A 
Screen View

2024-02-24 15:58 UTC, pixolopr approved these changes

2024-02-24 15:58 UTC, merged